"use client";
/* eslint-disable @next/next/no-img-element */
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2 } from "lucide-react";

type AdminDetailReport = { title: string; locationName: string; latitude: number; longitude: number; publicStatus: string; severity: string; incidentId: string; description: string; imageUrl: string | null; verificationStatus: string; user: { displayName: string | null; email: string } | null };
export function AdminReportDetail({ reportId }: { reportId: string }) {
  const [report, setReport] = useState<AdminDetailReport | null>(null); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { void fetch(`/api/admin/reports/${reportId}`, { cache: "no-store" }).then(async (r) => { const body = await r.json(); if (!r.ok) throw new Error(body.error); setReport(body.data.report); }).catch((e) => setError(e instanceof Error ? e.message : "Unable to load report.")); }, [reportId]);
  async function updateVerification(value: string) { setSaving(true); try { const r = await fetch(`/api/admin/reports/${reportId}/verification`, { method: "PATCH", headers: { "Content-Type": "application/json", Origin: window.location.origin }, body: JSON.stringify({ verificationStatus: value }) }); const body = await r.json(); if (!r.ok) throw new Error(body.error); setReport((current) => current ? { ...current, verificationStatus: body.data.verificationStatus } : current); } catch (e) { setError(e instanceof Error ? e.message : "Unable to update verification."); } finally { setSaving(false); } }
  if (error) return <main className="min-h-screen p-6"><p>{error}</p><Link href="/admin/reports">Back to reports</Link></main>;
  if (!report) return <main className="min-h-screen p-6 text-sm text-[var(--color-muted-foreground)]">Loading report...</main>;
  return <main className="min-h-screen bg-[var(--color-background)] p-4 sm:p-8"><div className="mx-auto max-w-4xl"><Link href="/admin/reports" className="inline-flex items-center gap-1 text-sm text-[var(--color-muted-foreground)]"><ArrowLeft className="h-4 w-4" /> Reports monitoring</Link><div className="mt-5 rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] p-5 sm:p-7"><div className="flex items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold">{report.title}</h1><p className="mt-1 text-sm text-[var(--color-muted-foreground)]">{report.locationName} · {report.latitude}, {report.longitude}</p></div><CheckCircle2 className="h-6 w-6 text-[var(--color-primary)]" /></div><dl className="mt-6 grid gap-4 sm:grid-cols-2"><div><dt className="text-xs text-[var(--color-muted-foreground)]">Reporter</dt><dd>{report.user?.displayName ?? report.user?.email ?? "Legacy anonymous"}</dd></div><div><dt className="text-xs text-[var(--color-muted-foreground)]">Public status</dt><dd>{report.publicStatus}</dd></div><div><dt className="text-xs text-[var(--color-muted-foreground)]">Severity</dt><dd>{report.severity}</dd></div><div><dt className="text-xs text-[var(--color-muted-foreground)]">Incident</dt><dd>{report.incidentId}</dd></div></dl><p className="mt-6 whitespace-pre-wrap text-sm leading-6">{report.description}</p>{report.imageUrl ? <img src={report.imageUrl} alt="Submitted report evidence" className="mt-6 max-h-[420px] w-full rounded-lg object-contain" /> : null}<label className="mt-7 block text-sm font-medium">Verification status<select disabled={saving} value={report.verificationStatus} onChange={(e) => void updateVerification(e.target.value)} className="mt-2 block rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] px-3 py-2"><option value="unreviewed">Unreviewed</option><option value="verified">Verified</option><option value="disputed">Disputed</option><option value="rejected">Rejected</option></select></label></div></div></main>;
}
